package br.com.gescolar.types;

public enum SerieEnum {
	JARDIM,
	PRE_ESCOLA,
	PRIMEIRA_SERIE,
	SEGUNDA_SERIE,
	TERCEIRA_SERIE,
	QUARTA_SERIE,
	QUINTA_SERIE,
	SEXTA_SERIE,
	SETIMA_SERIE,
	OITAVA_SERIE,
	PRIMIRO_ANO_SEGUNDO_GRAU,
	SEGUNDO_ANO_SEGUNDO_GRAU,
	TERCEIRO_ANO_SEGUNDO_GRAU,
}
